version: '3'
services:
  app:
    build:
      context: .
      args:
        DATABASE_URL: postgresql://postgres:password@db:5432/stackoverflowclone
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/stackoverflowclone
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stackoverflowclone
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prisma-studio:
    image: node:16  
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/stackoverflowclone  # Same database URL
    command: "npx prisma studio --port 5555"  # Automatically run Prisma Studio
    depends_on:
      - app

volumes:
  postgres_data:
