version: '3'
services:
  app:
    build:
      context: .
      args:
        DATABASE_URL: postgresql://postgres:password@db:5432/stackoverflowclone?schema=public
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/stackoverflowclone?schema=public
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stackoverflowclone
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
